[gemini]
GOOGLE_API_KEY= "your_GOOGLE_API_KEY"

[openai]
OPENAI_API_KEY="your_OPENAI_API_KEY"

[qdrant]
QDRANT_URL = "http://localhost:6333"

[langchain]
LANGSMITH_TRACING= "true"
LANGSMITH_API_KEY= "your_LANGSMITH_API_KEY"
LANGSMITH_PROJECT= "your_LANGSMITH_PROJECT"
LANGSMITH_ENDPOINT= "https://api.smith.langchain.com"
